### ISSUE TITLE
Support Adding Teams to repos

### ISSUE THREAD

**Issue by ajinkya** [mislav/gh-repo-collab#1]
Support the functionality to add teams to repos as well.
Some thing like this:
`gh repo-collab add <repo> {--user <username>|--team <teamname>} [--permission <string>]`

**Comment by ajinkya** [comment]
Will take a stab at adding this over the weekend.

**Comment by timbarton1966** [comment]
Any luck?

**Comment by genisd** [comment]
Just came here looking for the same.
