### ISSUE TITLE
Feat: Get repository from the current directory 

### ISSUE THREAD

**Issue by ShivamJoker** [mislav/gh-repo-collab#4]
It would be great if we could skip the repo variable and get it from the `gh repo status`.

**Comment by mislav** [comment]
Thanks for chiming in!

Note that the repo argument to `gh repo-collab list` is optional and is read from the current directory.

When editing collaborators, you _must_ specify the repository explicitly— this serves as a sort of a confirmation step. Without that, there is a risk you could run `gh repo-collab add <user>` in a wrong directory and leak a private project to an unintended recipient.

**Comment by ShivamJoker** [comment]
I see, fair enough.
